FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Directory.Build.props", "."]
COPY ["Directory.Packages.props", "."]

COPY ["src/Api/TraceApp.Api/TraceApp.Api.csproj", "src/Api/TraceApp.Api/"]
COPY ["src/Core/TraceApp.Application/TraceApp.Application.csproj", "src/Core/TraceApp.Application/"]
COPY ["src/Core/TraceApp.Domain/TraceApp.Domain.csproj", "src/Core/TraceApp.Domain/"]
COPY ["src/Infrastructure/TraceApp.Infrastructure/TraceApp.Infrastructure.csproj", "src/Infrastructure/TraceApp.Infrastructure/"]
RUN dotnet restore "src/Api/TraceApp.Api/TraceApp.Api.csproj"
COPY . .
WORKDIR "/src/src/Api/TraceApp.Api"
RUN dotnet build "./TraceApp.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./TraceApp.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TraceApp.Api.dll"]
